[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:494 checking whether the connectivity to the database is working
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:499 Cutting network for postgresql/1
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:505 checking for no connectivity between postgresql/1 and postgresql/3
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:505 checking for no connectivity between postgresql/1 and postgresql/2
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:512 checking for no connectivity between postgresql/1 and the controller
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:519 checking whether the connectivity to the database is not working
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:525 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:528 checking whether a new primary was elected
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:535 Restoring network for postgresql/1
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:539 waiting for cluster to become idle
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/1 [idle] active: Primary
  postgresql/2 [idle] active: Primary
  postgresql/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/2 [idle] active: Primary
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:544 waiting for the database service to be ready on postgresql/1
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:548 checking whether the connectivity to the database is working
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:199 checking that the former primary is now a replica
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:205 checking that all units are part of the same cluster
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:219 checking that no writes to the database were missed after stopping the writes
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:223 checking that the former primary is up to date with the cluster after restarting
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.4    unsupported  02:10:22Z

App                  Version  Status  Scale  Charm                Channel      Rev  Exposed  Message
postgresql           14.12    active      3  postgresql                          0  no       
postgresql-test-app           active      1  postgresql-test-app  latest/edge  191  no       received database credentials of the first database

Unit                    Workload  Agent  Machine  Public address  Ports     Message
postgresql-test-app/0*  active    idle   3        10.222.195.105            received database credentials of the first database
postgresql/1            active    idle   1        10.222.195.174  5432/tcp  
postgresql/2*           active    idle   2        10.222.195.192  5432/tcp  Primary
postgresql/3            active    idle   4        10.222.195.226  5432/tcp  

Machine  State    Address         Inst id        Base          AZ  Message
1        started  10.222.195.174  juju-a5f170-1  ubuntu@22.04      Running
2        started  10.222.195.192  juju-a5f170-2  ubuntu@22.04      Running
3        started  10.222.195.105  juju-a5f170-3  ubuntu@22.04      Running
4        started  10.222.195.226  juju-a5f170-4  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-3: 01:36:44 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:36:44 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:36:44 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:37:17 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:37:17 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:37:17 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:37:18 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:37:18 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:37:18 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:37:20 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:37:20 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:37:20 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 01:38:14 ERROR unit.postgresql/1.juju-log Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

machine-4: 01:46:31 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:46:31 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-3: 01:46:31 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 01:51:32 ERROR unit.postgresql/1.juju-log Failed to list PostgreSQL database users: connection to server at "10.222.195.74", port 5432 failed: timeout expired

unit-postgresql-1: 01:51:41 ERROR unit.postgresql/1.juju-log Failed to list PostgreSQL database users: connection to server at "10.222.195.74", port 5432 failed: timeout expired

machine-4: 02:02:01 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
machine-4: 02:02:01 ERROR juju.worker.uniter.metrics failed to close the collect-metrics listener: close unix /var/lib/juju/agents/unit-postgresql-3/2138949791/s: use of closed network connection
machine-4: 02:02:04 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [ff2b02] "machine-4" cannot open api: unable to connect to API: dial tcp 10.222.195.36:17070: connect: network is unreachable
machine-1: 02:07:47 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
machine-1: 02:07:47 ERROR juju.worker.uniter.metrics failed to close the collect-metrics listener: close unix /var/lib/juju/agents/unit-postgresql-1/911198621/s: use of closed network connection
machine-1: 02:07:51 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [ff2b02] "machine-1" cannot open api: unable to connect to API: dial tcp 10.222.195.36:17070: connect: no route to host
machine-1: 02:07:57 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [ff2b02] "machine-1" cannot open api: unable to connect to API: dial tcp 10.222.195.36:17070: connect: no route to host
machine-1: 02:08:03 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [ff2b02] "machine-1" cannot open api: unable to connect to API: dial tcp 10.222.195.36:17070: connect: no route to host
machine-1: 02:08:09 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [ff2b02] "machine-1" cannot open api: unable to connect to API: dial tcp 10.222.195.36:17070: connect: no route to host
machine-1: 02:08:19 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [ff2b02] "machine-1" cannot open api: unable to connect to API: dial tcp 10.222.195.36:17070: connect: no route to host
machine-1: 02:08:29 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [ff2b02] "machine-1" cannot open api: unable to connect to API: dial tcp 10.222.195.36:17070: i/o timeout
machine-1: 02:08:39 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [ff2b02] "machine-1" cannot open api: unable to connect to API: dial tcp 10.222.195.36:17070: connect: no route to host
machine-1: 02:08:53 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [ff2b02] "machine-1" cannot open api: unable to connect to API: dial tcp 10.222.195.36:17070: i/o timeout

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...